pipeline {
  environment {
    registry = "gionatale/fresh-pastry"
    registryCredential = 'docker-hub'
    dockerImage = ''
  }
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          serviceAccountName: jenkins
          containers:
          - name: maven
            image: maven:alpine
            command:
            - cat
            tty: true
          - name: kubectl-runner
            image: gionatale/kubectl-runner:1.0
          - name: build-container
            image: gradle:8.10.2-jdk-lts-and-current
            command:
            - cat
            tty: true
        '''
    }
  }
  stages {
        stage('Build') {
            //when {changeset "OrderService/**"}
            steps {
                container('build-container') {
                    sh 'gradle :OrderService:bootJar'
                }
            }
        }
        stage('Test') {
            //when {changeset "OrderService/**"}
            steps {
                container('build-container') {
                    echo 'Testing...'
                }
            }
        }
        stage('Create image') {
            //when {changeset "OrderService/**"}
            steps {
              dir('OrderService/ci-cd') {
                script {
                  dockerImage = docker.build registry + ":$BUILD_NUMBER"
                }
              }
            }
        }

        stage('Upload image') {
            //when {changeset "OrderService/**"}
            steps {
              dir('OrderService/ci-cd') {
                script {
                  docker.withRegistry( '', registryCredential ) {
                    dockerImage.push()
                  }
                }
              }
            }
        }
    }
}