pipeline {
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          serviceAccountName: jenkins
          containers:
          - name: maven
            image: maven:alpine
            command:
            - cat
            tty: true
          - name: kubectl-runner
            image: gionatale/kubectl-runner:1.0
          - name: build-container
            image: gradle:8.10.2-jdk-lts-and-current
            command:
            - cat
            tty: true
        '''
    }
  }
  stages {
        stage('Build') {
            steps {
                container('build-container') {
                    echo 'Building...'
                }
            }
        }
        stage('Test') {
            steps {
                container('build-container') {
                    echo 'Testing...'
                }
            }
        }
        stage('Deploy') {
            steps {
                container('kubectl-runner') {
                    echo 'Deploying...'
                }
            }
        }
    }
}