pipeline {
  environment {
    registry = "gionatale/fresh-pastry"
    registryCredential = 'docker-hub'
    dockerImage = ''
  }
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          serviceAccountName: jenkins
          containers:
          - name: maven
            image: maven:alpine
            command:
            - cat
            tty: true
          - name: kubectl-runner
            image: gionatale/kubectl-runner:1.0
          - name: build-container
            image: gradle:8.10.2-jdk-lts-and-current
            command:
            - cat
            tty: true
          - name: image-builder
            image: gcr.io/kaniko-project/executor:debug
            command:
            - /busybox/cat
            tty: true
            volumeMounts:
            - name: gitlab-registry-auth-config-file
              mountPath: /kaniko/.docker/
          volumes:
          - name: gitlab-registry-auth-config-file
            secret:
              secretName: gitlab-registry-auth-config-file
        '''
    }
  }
  stages {
        stage('Build') {
            //when {changeset "OrderService/**"}
            steps {
                container('build-container') {
                    //sh 'gradle :OrderService:bootJar'
                }
            }
        }
        stage('Test') {
            //when {changeset "OrderService/**"}
            steps {
                container('build-container') {
                    echo 'Testing...'
                }
            }
        }
        stage('Upload Image') {
            //when {changeset "OrderService/**"}
              steps {
                container(name: 'image-builder', shell: '/busybox/sh') {
                  //dir('ci-cd') {
                    sh '''
                      #!/busybox/sh
                      # /kaniko/executor -f `pwd`/Dockerfile -c `pwd` --cache=true --destination=registry.gitlab.com/gionatale/freshpastry/order-service:${BUILD_NUMBER}
                      pwd
                      ls
                    '''
                  //}
                }
              }
        }
    }
}